### ISSUE TITLE
Alinhamento com os lideres de back-end

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#10]
Alinhar com os líderes do back-end sobre como commitar o projeto back-end para o repositório do projeto.

**Comment by NikolasMatias** [comment]
Nós alinhamos com o Gabriel Barbosa e com o Eduardo Horst. Os únicos que já fizeram commits no projeto arquitetura de teste até agora, para que eles possam enviar o que fizeram do projeto teste encontrado no link: [Fabrica Teste Arquitetura](https://github.com/gabrielbo1/fabrica-testearquitetura-2017-1).
