### ISSUE TITLE
Alinhar sobre o padrão de Banco de Dados com os representantes de Back-end

### ISSUE THREAD

**Issue by gilmarfilho** [fabrica-ufg-2017-2/portal-da-transparencia#113]

**Comment by ronynogueiras** [comment]
O padrão para a nomenclatura dos itens relativos ao banco de dados deve ser o estabelecido no Modelo Entidade Relacionamento (MER) que foi proposto, os nomes de tabelas e atributos devem seguir os nomes atribuídos no modelo.
