### ISSUE TITLE
[Gestão de portaria] Corrigir protótipo listagem de portarias

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#161]
O protótipo deve conter
 - [x] Search bar (Nome do envolvido, código da portaria, responsabilidade) 
 - [x] Filtro de período
 - [x]  Botão pesquisar (Questão de usabilidade fica a critério do criado do protótipo)
 - [x] Status (Inativa/Ativa)
 - [ ] Filtrar por tipo de portaria(Emitida/recebida) 

[Documento de casos de uso](https://docs.google.com/document/d/13ykdS03T-eBqGKNHKYavDTvckdahzZGNUKo3Y0MQYbw/edit?usp=sharing)
Os casos de uso são os GES - 1 até GES - 2(<- exclusório)

**Comment by Eddyosos** [comment]
O ultimo filtro (filtrar por tipo de portaria) é impossível dado o modelo de dados.

**Comment by Eddyosos** [comment]
Resultado: https://drive.google.com/open?id=0B7jMzvpjqKobajR4VnR6OXZZbVE
