### ISSUE TITLE
[Gestão de portaria] Criar protótipo portaria aberta

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#163]
Definimos que as portarias seriam listadas e que ao clicar em uma o sistema exibiria todas as informações cadastradas nela, faz-se necessário criar o protótipo de como seria essa portaria aberta.

**Comment by Eddyosos** [comment]
Resultado: https://drive.google.com/open?id=0B7jMzvpjqKobaWlzSEZQWTBxNjA
