### ISSUE TITLE
[Gestão de portarias] Criar caso de uso filtrar responsabilidade por nome da responsabilidade

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#177]
Como descrito em #155

**Comment by jorgetbruno** [comment]
Protótipo anexado ao caso de uso GES-24 [aqui](https://docs.google.com/document/d/13ykdS03T-eBqGKNHKYavDTvckdahzZGNUKo3Y0MQYbw/edit?usp=sharing
)
