### ISSUE TITLE
Elicitação de Requisitos com o Marcelo Quinta

### ISSUE THREAD

**Issue by NikolasMatias** [fabrica-ufg-2017-2/portal-da-transparencia#18]
Reunião de Elicitação de Requisitos com o Marcelo Quinta. Necessário a criação de Ata da Reunião.

**Comment by jorgetbruno** [comment]
Ata da reunião pode ser encontrada [aqui](https://docs.google.com/document/d/1-GYm7FpqMX2ZpcQejjpAlKx6TnCXTJ3DTDUID4H57ck/edit?usp=sharing)
