### ISSUE TITLE
Criação protótipo login inválido

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#181]
Como descrito em #139

**Comment by erivanbarbosa** [comment]
Completo.

Protótipos disponíveis em  [Protótipo/Gestão de Portarias](https://drive.google.com/drive/folders/0B7jMzvpjqKobTnFtM1NTZk40S0k)

- gestão login inválido.png
- gestão login inválido.epgz
