### ISSUE TITLE
[Gestão de portarias] Corrigir caso de uso GES-2

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#186]
Como descrito em #123

**Comment by erivanbarbosa** [comment]
Completo e disponível em: [Casos de Uso - Gestão de Portarias](https://docs.google.com/document/d/13ykdS03T-eBqGKNHKYavDTvckdahzZGNUKo3Y0MQYbw/edit)

- Foi removido o fluxo de pesquisa por período, porque o protótipo de tela linkado ao caso de uso não possui opção para este tipo de pesquisa.
- Foi adicionado um novo fluxo para pesquisa por tipo de pessoa, uma vez que esta opção existe no protótipo, mas não existia no caso de uso.
