### ISSUE TITLE
Validar protótipos do Módulo da Gestão

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#190]
Como descrito em #98

**Comment by guicaixeta** [comment]
Versão inicial aprovada pelo Diretor, Coordenador e Professor Stakeholder em reunião com os Assigness na Issue. Uma nova reunião foi solicitada com o Coordenador Administrativo para que a versão final do protótipo seja aprovada, aguardando resposta do email.
