### ISSUE TITLE
Validar Casos de Uso

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#199]
Realizar validação dos casos de uso com aplicação do checklist.

**Comment by adryanoalf** [comment]
A validação dos casos de uso e seus protótipos pode ser visto em: https://docs.google.com/document/d/14PpugHiP6jPmZO-hTxrRfZqkpTzVnJe3nl2yqw8BW0o/edit

Erros encontrados nos protótipos apenas

PES-1: Não possui a definição do período pelo ator.
PES-2: Não possui a definição de quantidade de pesquisadores.
PES-5: O modelo foge totalmente do padrão e não possui tudo informado no caso de uso.
PES-7: O modelo foge totalmente do padrão.
PES-8: A interface não segue o estilo estipulado pela equipe.
