### ISSUE TITLE
Validar diagrama de casos de uso e de sequência

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#200]
Realizar a validação do diagrama de casos de uso e do diagrama de sequência criados. Definir e aplicar um checklist.

**Comment by adryanoalf** [comment]
O documento de análise pode ser encontrado em: https://docs.google.com/document/d/14PpugHiP6jPmZO-hTxrRfZqkpTzVnJe3nl2yqw8BW0o/edit

Diagrama de casos de uso: Os casos de uso 8 e 9 não estão presentes no diagrama, e por conta disso as conexões estão incompletas também.

Diagrama de sequência: Não estão presentes entre os documentos, portanto não passou na avaliação de qualidade.
