### ISSUE TITLE
[Gestão de portarias] Criar caso de uso Visualiza perfil

### ISSUE THREAD

**Issue by erivanbarbosa** [fabrica-ufg-2017-2/portal-da-transparencia#227]

**Comment by erivanbarbosa** [comment]
Finalizado, ainda é necessário validar com o professor.

**Comment by Eddyosos** [comment]
Observar comentário: https://docs.google.com/document/d/13ykdS03T-eBqGKNHKYavDTvckdahzZGNUKo3Y0MQYbw/edit?disco=AAAABaZ3qTs
