### ISSUE TITLE
validar protótipo de visualização de perfil

### ISSUE THREAD

**Issue by erivanbarbosa** [fabrica-ufg-2017-2/portal-da-transparencia#248]

**Comment by erivanbarbosa** [comment]
Validar o prototipo [visualiza perfil](https://github.com/fabrica-ufg-2017-2/portal-da-transparencia/issues/238).

- [ ] Verificar consistência com modelo de dados.
- [ ] Verificar consistência com caso de uso do protótipo.
- [ ] Verificar consistência com outros casos de uso.

**Comment by jorgetbruno** [comment]
Este caso de uso foi dividido em 2: GES - 38 e GES - 40.
GES - 38 - Lista os usuários.
GES - 40 - Filtra por email.

Ambos estão em conforme com o modelo de dados.
