### ISSUE TITLE
Criação do Diagrama de Sequencia

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#252]
Criar o **diagrama de comunicação** entre as classes que participarão do **Caso de Uso 1**. Um **modelo** será criado pelo @gabrielbo1 , pois a arquitetura que guia a comunicação é a mesma. Enquanto o modelo não é criado, **pesquisar sobre diagramas de comunicação**, sua notação e descrições para produzir um artefato com **maior qualidade final**.

Entrar em contato com o @gabrielbo1 para saber quando o modelo estará pronto.

Prazo estimado: 4 horas
Data máxima entrega: 10-11-17 18:49

**Comment by eliezerdejj** [comment]
Acho que está havendo falha na comunicação, é diagrama de sequencia.

**Comment by vinilopes03** [comment]
Já resolvido caro @eliezerdejj

**Comment by eliezerdejj** [comment]
validado

**Comment by jhemarcos** [comment]
Validado.

**Comment by pedlop** [comment]
Validado.

**Comment by eliezerdejj** [comment]
Foi validado
