### ISSUE TITLE
Diagrama de sequência - backend - EXT01

### ISSUE THREAD

**Issue by gilmarfilho** [fabrica-ufg-2017-2/portal-da-transparencia#261]

**Comment by michelberigo** [comment]
Necessário duas pessoas para criar este diagrama. Discutido em reunião 06/11

**Comment by BrunoMessias** [comment]
@gilmarfilho @michelberigo @joaohhenriq @ronynogueiras 
Esse é o diagrama que falta, e provavelmente o mais dificil. Eu vou me designar para a tarefa, mas precisarei de ajuda. Alguém se habilita?

**Comment by michelberigo** [comment]
Eu me habilito. Vamos trabalhar neste diagrama Segunda-Feira a noite, que é quando todos nós nos encontramos

**Comment by michelberigo** [comment]
Conteúdo informativo acerca de Diagrama de Sequência: http://www.dsc.ufcg.edu.br/~jacques/cursos/map/html/uml/diagramas/interacao/sequencia.htm

**Comment by BrunoMessias** [comment]
Documento revisado e aprovado com as seguintes correções
* Url modificada para extensao/projeto
