### ISSUE TITLE
[Gestão de portarias] Corrigir casos de uso relacionados a Usuários

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#270]
Observar o [diagrama de casos de uso](https://drive.google.com/file/d/0B7jMzvpjqKobYTVaeERnZjZuWkk/view?usp=sharing) para [casos de uso](https://docs.google.com/document/d/13ykdS03T-eBqGKNHKYavDTvckdahzZGNUKo3Y0MQYbw/edit?usp=sharing) relacionados.
Ainda observe se à alguma inconsistencia entre eles

**Comment by NikolasMatias** [comment]
# Relatório de Validação e Modificações

Segue agora a lista de modificações feitas durante a correção.

- Nome do GES-5 estava incoerente. Alterado de Cadastro de Usuário para Cadastra redator conforme está no diagrama.
- No Caso de Uso GES-7 atualizamos o Cenário Principal e adicionamos um nov Cenário Secundário.
- A opção "Nome" foi adicionado ao usuário. Alterações foram necessárias em GES-5 e GES-30.
- Alterações feitas no GES-30, acrescentei um botão para editar dentre o que será listado quando exibir o perfil. Além disso, alterei a forma de nomeação da ordenação dos Cenários que estava fora do padrão.
- Caso de Uso GES-33 gerado para tratar o "Editar perfil".
- Novo caso de uso criado para a opção de Alterar senha dentro do perfil. Já foi adicionado ao Diagrama e o Caso de Uso GES-34 foi criado para ele.
- Os Casos de Uso GES-35 (Visualiza redator), GES-36 (Edita redator), GES-37 (Deleta redator) e GES-38 (Listar redatores) foram criados para atender ao modelo do Diagrama.
- Diagrama alterado para atender à realidade apresentada nos Casos de Uso.
