### ISSUE TITLE
[Gestão de portaria] Corrigir caso de uso criar portaria

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#292]
Portaria agora conta com um caso de uso para identificar o orgão emissor, desta forma o caso de uso deve ser adaptado.

**Comment by NikolasMatias** [comment]
## Relatório das alterações feitas

Segue agora a lista de mudanças que foram feitas para essa issue:

- Alteração feita para o Caso de Uso GES-4.
- Várias inconsistências relatadas pela equipe que está trabalhando no front-end.  A Issue #302 foi criada para tratar da revisão e correção delas.
