### ISSUE TITLE
Casos de Uso

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#31]
Produzir a definição dos **casos de uso** com base nos dados coletados nas fases anteriores. Os documentos base e a especificação produzida devem ficar na [pasta de requisitos do grupo de pesquisa no drive](https://drive.google.com/drive/u/0/folders/0B5YQ6M8aJrbSc1o3dl8yV1lWcmc).

**Comment by adryanoalf** [comment]
Casos de uso revisado e prontos para a entrega.
