### ISSUE TITLE
[gestão de portarias] Corrigir protótipos relacionados a Pessoas 

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#313]
Validar se os protótipos relacionados a pessoas estão em conformidade com os casos de uso.

- Casos de uso podem ser encontrados [aqui](https://docs.google.com/document/d/13ykdS03T-eBqGKNHKYavDTvckdahzZGNUKo3Y0MQYbw/edit?usp=sharing)

- Protótipos podem ser encontrados [aqui](https://drive.google.com/open?id=0Bws5PAa3KmhoNkpaZDY2QWtQWWc)

Atividade original #273

**Comment by erivanbarbosa** [comment]
Os protótipos até podem ser encontrados (porém estão na pasta de protótipos do portal da transparência, e não da gestão de portarias), porém o documento de casos de uso não possui casos de uso para pessoa @jorgetbruno
