### ISSUE TITLE
Criar diagrama de classes front para o PES-6

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#316]
Criar diagrama de classes front para o PES-6

Prazo estimado: **06 horas**
Data máxima entrega: **10-11-17 18:49**

**Comment by pedlop** [comment]
https://drive.google.com/drive/folders/0B5YJvZt93T_gSm14VFJVcGV6bkU
Arquivo: Front - Diagrama de Classes PES-6
