### ISSUE TITLE
Validação geral da arquitetura - interna

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#318]
Realizar validação de todos os componentes da arquitetura, para então ser enviado para validação pelos stakeholders.

Prazo estimado: **01 hora**
Data máxima entrega: **10-11-17 18:49**

**Comment by eliezerdejj** [comment]
deve ser feito até quarta feira, acredito que deve ser feito só a validação final e ver se tudo está dentro do especificado.
