### ISSUE TITLE
Validação geral da arquitetura - stakeholders

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#325]
Enviar documento de resumo da arquitetura para validação de todos os componentes pelos stakeholders.

Prazo estimado: **01 hora**
Data máxima entrega: **10-11-17 18:49**

**Comment by eliezerdejj** [comment]
foi validado, algumas sugestões foram dadas para correções pequenas, nada que gere muito esforço
