### ISSUE TITLE
Revisão e Validação de Entregáveis

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#34]
Realizar a **revisão e validação dos entregáveis** produzidos nas isses [30](https://github.com/fabrica-ufg-2017-2/portal-da-transparencia/issues/30), [31](https://github.com/fabrica-ufg-2017-2/portal-da-transparencia/issues/31), [32](https://github.com/fabrica-ufg-2017-2/portal-da-transparencia/issues/32) e [33](https://github.com/fabrica-ufg-2017-2/portal-da-transparencia/issues/33). Caso haja alterações a serem realizadas, comunicar ao responsável o quanto antes via slack. Verificar via slack quando os entregáveis já estarão prontos para revisão.

**Comment by adryanoalf** [comment]
O documento foi revisado e o caso de uso PES-2 precisa ser mesclado com os outros grupos para exibir qualquer pessoa cadastrada no sistema. Os protótipos não foram revisados por estarem ausentes na documentação até o momento.
