### ISSUE TITLE
Reunião dos lideres 10/11

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#343]
Reunião dos líderes do dia 10/11 para alinhamento de estado e padronização de artefatos

**Comment by eliezerdejj** [comment]
[Link para Ata](https://docs.google.com/document/d/1-IYoH3OvCTPSPyRPBDEOQlqLEyiJN43NpnAucmqEeX0/edit)
[Link para o Áudio da reunião](https://drive.google.com/file/d/17bGb1PJ1iDGeIfyE7bR1gZ43Mq_JBw_7/view?usp=sharing)
