### ISSUE TITLE
Unir os modelos de dados

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#40]
Foi definido que todos os grupos deveram entregar os modelos de dados de suas áreas até dia 21-09-2017 as 12h, o responsável por este card deverá unir os modelos.

**Comment by gabrielbo1** [comment]
Concluído conforme imagem https://drive.google.com/open?id=0B9CkmX5J20PiWEN5VFFwY0lQdzA
