### ISSUE TITLE
Corrigir Diagrama de Classe

### ISSUE THREAD

**Issue by michelberigo** [fabrica-ufg-2017-2/portal-da-transparencia#406]
* Criar Diagrama de Classe para o Front-End;
* Corrigir Diagrama de Classe (Back-End) de acordo com o grupo de Pesquisa/Ensino.

**Comment by joaohhenriq** [comment]
Foram corrigidas regras de negócio relacionados com as classes equipe, papel e pessoa, uma vez que as ligações entre elas foram atualizadas para condizer com o modelo de dados.

**Comment by BrunoMessias** [comment]
O diagrama de classe de back-end foi validado, as correções foram apenas foram na legibilidade do diagrama
