### ISSUE TITLE
Criar o modelo de dados do módulo de gestão

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#41]
Um dos entregáveis do primeiro milestone é um modelo de dados do projeto, foi definido que o modelo de cada grupo deve ser entregue dia 21-09-2017 até as 12h.

**Comment by Eddyosos** [comment]
Ao observar o entregavel, acredito que tenha sido erroneamente marcado como concluido, retornarei para fazendo

**Comment by NikolasMatias** [comment]
O Modelo já foi feito e está aguardando revisão.

**Comment by Eddyosos** [comment]
- [ ]
