### ISSUE TITLE
[Portal da transparência] Correções nos casos de uso

### ISSUE THREAD

**Issue by TiagoDamascena** [fabrica-ufg-2017-2/portal-da-transparencia#423]
Correções nos casos de uso do portal da transparência

- [x] Corrigir casos secundários do GES-1 para não conter os filtros (já estão em GES separados)
- [x] Criar Caso de Uso visualizar detalhes da portaria
- [x] Criar Caso de Uso visualizar detalhes do designado

**Comment by guicaixeta** [comment]
Criados casos de uso GES-21 e GES-22 respectivamente

**Comment by guicaixeta** [comment]
Corrigido caso de uso GES-01
