### ISSUE TITLE
Validar protótipos 

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#43]
Um dos entregáveis do primeiro milestone são os protótipos do sistema, cabe ao responsável desta atividade validar os protótipos, está atividade deve ser entregue até dia 22-09-2017

**Comment by jorgetbruno** [comment]
Colaborador @gilmarfilho foi marcado erroneamente, o colaborador @josimarMorais é o verdadeiro responsável pela atividade.

**Comment by josimarMorais** [comment]
Até o momento, só consegui achar o protótipo da tela inicial do portal da transparência, criado pelo @TiagoDamascena, onde ficou muito bom. Aguardando os outros protótipos para validação.

**Comment by jorgetbruno** [comment]
O issue que deu origem a este pode ser encontrado aqui #39
