### ISSUE TITLE
Modelo de dados da gestão para o portal da transparência

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#47]

**Comment by Eddyosos** [comment]
Feito no arquivo https://drive.google.com/open?id=0B7jMzvpjqKobU0UzNTJpcWVoN2M

**Comment by erivanbarbosa** [comment]
Modelo de dados validado!

Artefatos gerados para validação podem ser consultados na issue #52
