### ISSUE TITLE
Elicitar requisitos com Enio, coordenador administrativo do Inf.

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#5]
Enio é o coordenador administrativo do instituto de informatica, ele é o responsável por manter o registro de portarias do instituto, tornando-o um dos principais utilizadores do modulo de gestão.

obs: Notificar o professor Juliano Lopes de Oliveira sobre quando irá ocorrer está reunião de elicitação, pois o mesmo gostaria de participar.

**Comment by guicaixeta** [comment]
Conforme combinado na semana passada com o Enio, foi enviado a ele hoje um email marcando a reuniao para essa semana, o mesmo se prontificou que nao podia na semana passada por isso nao foi realizado ainda tal reuniao.

**Comment by jorgetbruno** [comment]
Reunião ocorreu dia 20/09/2017
