### ISSUE TITLE
Definir riscos do modulo de gestão

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#51]

**Comment by Eddyosos** [comment]
Riscos foram elvantados no documento [Riscos de projeto](https://docs.google.com/document/d/1ZbLEJxfqRUW8_BhnIPy46IOlWq_NCby8xP7VyJCbFRc)
O mesmo  foi enviado para o Juliano para avaliação

**Comment by jorgetbruno** [comment]
@Eddyosos Acho que deveria conter o risco dos outros grupos não entregarem a parde deles.

**Comment by Eddyosos** [comment]
Concordo, adicionado

**Comment by Eddyosos** [comment]
De acordo com o Juliano

1. Descrição do risco deveria especificar: a) os eventos ou condições que causam o risco; b) o problema que pode ocorrer devido à ocorrência do item a); e c) o efeito ou resultado do problema.Exemplo: a) as partes interessadas não estão disponíveis em tempo integral para o projeto; b) pode ocorrer demora na aprovação de requisitos; c) ou o projeto atrasará, aguardando a aprovação, ou poderá haver retrabalho, pela construção baseada em requisitos que não serão aprovados. 
1. Em vez de frequência, estimar a probabilidade de a) ocorrer e de isso causar a ocorrência de b). Essa probabilidade pode ser em escala numérica (entre 1% e 99%), ou em escala qualitativa (alta, média, baixa probabilidade).
Avaliar a criticidade considerando não apenas o impacto no prazo (atraso), mas nas outras variáveis relevantes do projeto: esforço/custo, escopo/atendimento de expectativas, qualidade do produto e do processo. Essa criticidade pode ser em escala numérica (entre 1 ponto e 99 pontos, sendo 1 ponto definido em termos de um impacto pequeno em cada uma das variáveis), ou em escala qualitativa (alta, média, baixa criticidade).
1. Em vez de prevenir/adiantar/mitigação poderia haver uma estratégia para o risco, que envolve ações de aceitar, transferir, mitigar e contingenciar.
1. No monitoramento, é essencial atribuir uma responsabilidade individual pelo risco, ou seja, deve haver um indivíduo responsável pelo monitoramento de cada risco.
1. É importante comunicar os riscos para a equipe de desenvolvimento e para as partes interessadas. Para isso pode ser criado um relatório de estado do projeto, indicando a tendência temporal de cada risco (risco estável, risco aumentando probabilidade, risco diminuindo probabilidade, novo risco, risco eliminado, risco ocorrido no período, etc.).

**Comment by Eddyosos** [comment]
Alterações foram feitas para melhor atender o feedback do juliano

**Comment by jorgetbruno** [comment]
O documento pode ser encontrado neste [Link](https://docs.google.com/document/d/1ZbLEJxfqRUW8_BhnIPy46IOlWq_NCby8xP7VyJCbFRc/edit?usp=sharing)
