### ISSUE TITLE
Validar modelo de dado da transparencia

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#52]
Fazer validação do modelo de dados do portal da transparencia contra os casos de uso do portal da transparencia

**Comment by erivanbarbosa** [comment]
Finalizado.

Adicionei os arquivos no drive no link : https://drive.google.com/drive/folders/0B7cIZa2mYkjuZVZ3U1hsdGZIaFU

Se a localização não for adequada sinta-se livre pra mover para onde desejar ou me informar pra que mova.
Aguardo confirmação.


[modelo_portal_transparencia.pdf](https://github.com/fabrica-ufg-2017-2/portal-da-transparencia/files/1345095/modelo_portal_transparencia.pdf)
![modelo_portal_transparencia](https://user-images.githubusercontent.com/11925370/31026966-d8ee31be-a51e-11e7-9b36-4cf40ee0e9d7.png)
