### ISSUE TITLE
Refatoração de Protótipos

### ISSUE THREAD

**Issue by jhemarcos** [fabrica-ufg-2017-2/portal-da-transparencia#54]
Realizar a refatoração dos protótipos conforme os casos de uso. Conforme comentários do stakeholder Juliano, os protótipos devem ser de maior **baixo nível** possível e devem ser **descritivos** com o caso de uso relacionado.

**Comment by pedlop** [comment]
Todos os protótipos refatorados:
https://drive.google.com/drive/folders/0B_yK6K2MKv1aQ3lxMExDZWdPZTg
