### ISSUE TITLE
Protótipos do modulo de gestão

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#67]

**Comment by jorgetbruno** [comment]
@TiagoDamascena Acho que seria pertinente ter as telas dos casos de uso GES-4, GES-5, GES-6, GES-8 e GES-10

**Comment by TiagoDamascena** [comment]
@jorgetbruno Estou fazendo nesse momento.

**Comment by jorgetbruno** [comment]
Os protótipos podem ser encontrados neste [Link](https://drive.google.com/drive/folders/0B7jMzvpjqKobYTlkMlp1ZlRqYzQ?usp=sharing)
