### ISSUE TITLE
Separar casos da gestão em atividades

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#75]
Usar os casos de uso da gestão (gerenciador de portarias) em atividades, de forma que fique claro as atividades de back/front, rastreabilidade para o caso de uso & dependência entre atividades.

**Comment by erivanbarbosa** [comment]
Resultado [Módulos do Portal](https://docs.google.com/document/d/1gOvRI96yOvygl9qc2HUXKcsPYxC9Fwdc6AMICiyt6-w/edit)

**Comment by Eddyosos** [comment]
OK
