### ISSUE TITLE
Separar casos de uso do portal em atividades

### ISSUE THREAD

**Issue by Eddyosos** [fabrica-ufg-2017-2/portal-da-transparencia#76]
Usar os casos de uso da gestão (portal da transparência) em atividades, de forma que fique claro as atividades de back/front, rastreabilidade para o caso de uso & dependência entre atividades.

**Comment by Eddyosos** [comment]
Resultado: [Modulos do portal](https://docs.google.com/document/d/1IXzlMhlqij8HDfj24Pj6diRbE4RDYNvyOsVIGcE2AV4/edit?usp=sharing)

**Comment by jorgetbruno** [comment]
Validado #93
