### ISSUE TITLE
Especificar requisitos

### ISSUE THREAD

**Issue by jorgetbruno** [fabrica-ufg-2017-2/portal-da-transparencia#9]

**Comment by guicaixeta** [comment]
documento de especificação sendo desenvolvido no https://docs.google.com/document/d/1Fs3uMoa2aEgDqp46mdyeUs68CjGqHbaqbkJh9LHBpRg/edit?usp=sharing

**Comment by guicaixeta** [comment]
Casos de uso sendo elicitados no https://docs.google.com/document/d/1Fs3uMoa2aEgDqp46mdyeUs68CjGqHbaqbkJh9LHBpRg/edit?usp=sharing
